_BASE_: "./clip_resnet_yfcc_debug.yaml"
DATASETS:
  TRAIN: ("imgtxtpairs",)
  FACTORY_TRAIN: ("CLIPImgTxtPairTSVDataset",)
  PATH_TRAIN: ("/mnt/data_storage/coco-caption/train2017",) # ("/home/v-yiwuzhong/projects/azureblobs/vlpdatasets/yfcc100m/val",)
  # TEST: ("imagenet",)
  # FACTORY_TEST: ("CLIPImgTSVDataset",)
  # PATH_TEST: ("/mnt/data_storage/imagenet-tsv/val.tsv",)